### ISSUE TITLE
[Bug] Gatsby docs aren't compiling

### ISSUE THREAD

**Issue by chrisgervang** [visgl/hubble.gl#179]
**Describe the bug**
There is an error generating the website during the gatsby start-up within the markdown plugin.

**To Reproduce**
```bash
node -v
>> v14.17.5
```
```bash
git clone git@github.com:visgl/hubble.gl.git
yarn boostrap
cd website
yarn
yarn start
```

**Expected behavior**
The website should compile all the existing markdown files, like these: https://github.com/visgl/hubble.gl/tree/master/docs/api-reference

**Screenshots**
![Screen Shot 2021-10-07 at 3 08 12 PM](https://user-images.githubusercontent.com/2461547/136857569-d10d126a-8d6a-4682-a59e-c216bb720345.png)
![Screen Shot 2021-10-07 at 3 08 20 PM](https://user-images.githubusercontent.com/2461547/136857572-a24cd5a4-c5e9-4ddf-a434-b46a27edcafd.png)
![Screen Shot 2021-10-07 at 3 09 42 PM](https://user-images.githubusercontent.com/2461547/136857575-91428f9f-f438-401f-ac81-917cfb7569c4.png)
![Screen Shot 2021-10-07 at 3 50 18 PM](https://user-images.githubusercontent.com/2461547/136857580-228303ec-521b-4b7f-9e42-8f05b6333145.png)
![Screen Shot 2021-10-07 at 3 52 54 PM](https://user-images.githubusercontent.com/2461547/136857583-87fcd429-5966-40ea-b7d7-5598b0762df7.png)
![Screen Shot 2021-10-11 at 2 18 57 PM](https://user-images.githubusercontent.com/2461547/136857585-ed6d957f-6a96-4fc2-bd43-aefdf013090a.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version 94

**Additional context**

**Comment by chrisgervang** [comment]
Trying `brew install node@14 && brew link --overwrite node@14` 
```
==> Upgrading node@14
  14.17.5 -> 14.18.0_1
```
Flushing all cache/node_modules.
It didn't seem to make a difference.

**Comment by mletic** [comment]
@chrisgervang I was able to run the app following your steps, no issues detected except for some `ESLintErrors` displayed by  Gatsby as warnings.

I am running `v12.19.0` of Node.
